---
  - name: Create Ludus Windows Directory
    ansible.windows.win_file:
      path: "C:\\ludus"
      state: directory

  - name: Download Windows Velociraptor Binary
    ansible.builtin.win_get_url:
      url: "https://github.com/Velocidex/velociraptor/releases/download/{{ velociraptor_version }}/velociraptor-{{ velociraptor_version_patch }}-windows-amd64.exe"
      dest: "C:\\ludus\\velociraptor.exe"

  - name: Copy Client Config to VM
    ansible.windows.win_copy:
      src: "/tmp/client.config.yaml"
      dest: "C:\\ludus\\client.config.yaml"

  - name: Install Velociraptor Agent
    ansible.windows.win_shell: "& C:\\ludus\\velociraptor.exe --config C:\\ludus\\client.config.yaml service install"